const remedyImg = {
    '0': "https://static.wikia.nocookie.net/naruto/images/8/87/Zero_tails.PNG/",
    '8': "https://static.wikia.nocookie.net/naruto/images/4/40/Zaku_Abumi.PNG",
    '25': "https://static.wikia.nocookie.net/naruto/images/1/19/Akaboshi.PNG",
    '31' :[
        "https://static.wikia.nocookie.net/naruto/images/a/aa/Akane.png",
        "https://static.wikia.nocookie.net/naruto/images/8/84/Akane_as_a_teenager.PNG"
        ],
    '32': "../../imgRemedy/characters_img/id32.jpg",
    '33': 'https://static.wikia.nocookie.net/naruto/images/4/46/Akane%27s_father.PNG',
    '60': "https://static.wikia.nocookie.net/naruto/images/3/3c/Amaru.PNG",
    '61': "https://static.wikia.nocookie.net/naruto/images/e/e8/Amayo.PNG",
    '78': [
        'https://static.wikia.nocookie.net/naruto/images/c/cd/Animal_Path.png',
        'https://static.wikia.nocookie.net/naruto/images/4/43/Animal_Path_Alive.PNG'
         ],
    '105': "https://static.wikia.nocookie.net/naruto/images/c/c8/Baiu.PNG",
    '120': "https://static.wikia.nocookie.net/naruto/images/9/95/Benten.PNG",
    '143': "https://i.pinimg.com/736x/89/5e/d5/895ed5a37f77d8c142a99fc83c208087.jpg",
    '148': "https://preview.redd.it/9hlwyq2u0ww71.jpg?width=538&format=pjpg&auto=webp&s=8bcc0bf1ffa35b28f66f0281a51a5d0ded1a16df",
    '158': "https://static.wikia.nocookie.net/naruto/images/0/09/Chushin.PNG",
    '162': "https://static.wikia.nocookie.net/naruto/images/c/c0/Crimson_Fist_full.png/", 
    '222': "https://static.wikia.nocookie.net/naruto/images/4/45/Fud%C5%8D.PNG",
    '224': "https://static.wikia.nocookie.net/naruto/images/b/b5/Fuen.PNG",
    '266': ["https://static.wikia.nocookie.net/naruto/images/e/e1/Gamakichi.PNG",
            "https://static.wikia.nocookie.net/naruto/images/0/08/Gamakichi.png"
            ],
    '272': "https://static.wikia.nocookie.net/naruto/images/f/fe/Gameru.PNG",
    '285': "https://static.wikia.nocookie.net/narutofanon/images/6/6b/Garyou.jpg",
    '286': "https://static.wikia.nocookie.net/naruto/images/4/43/Gatai.png",
    '300': "https://static.wikia.nocookie.net/naruto/images/3/3a/Genmai.PNG",
    '308': "https://static.wikia.nocookie.net/naruto/images/1/1d/Queen_Bee.PNG",
    '313': "https://static.wikia.nocookie.net/naruto/images/f/f5/Giant_Drill-Beaked_Bird.PNG",
    '317': "https://static.wikia.nocookie.net/naruto/images/5/5a/Multi_headed_dog2.PNG",
    '318': "https://static.wikia.nocookie.net/naruto/images/4/4b/Giant_Ram.PNG",
    '330': "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK26H_56hzILpD1DLbh3KkuMLhDRUz7f1IVXgKJWd4hFMrlj_6IQoCK_c6Nmc2_bpdDxA&usqp=CAU",
    '362': "https://i.pinimg.com/originals/29/3b/55/293b557742ff5e0a28ee0d26bd3ebb79.png",
    '378': 'https://static.wikia.nocookie.net/naruto/images/c/c0/Hato.PNG',
    '390': 'https://static.wikia.nocookie.net/naruto/images/a/a6/Hidero.PNG',
    '420': "https://static.wikia.nocookie.net/naruto/images/0/0a/H%C5%8Dsei.JPG",
    '448': "https://static.wikia.nocookie.net/naruto/images/0/0d/Hanzo_and_The_Salamander.PNG",
    '474': "https://static.wikia.nocookie.net/xianb/images/d/d2/Boruto_Naruto_Next_Generations_Episode_120_0534.jpg",
    '507': "https://static.wikia.nocookie.net/naruto/images/a/a8/Jibachi_Kamizuru.PNG",
    '513': 'https://static.wikia.nocookie.net/naruto/images/5/55/Jimei.JPG/',
    '515': "https://static.wikia.nocookie.net/naruto/images/2/21/Profile_Jiraiya.PNG",
    '525': 'https://static.wikia.nocookie.net/narutooriginals/images/a/a9/Kaede_Kazamatsuri_Part_II.png',
    '526': "https://static.wikia.nocookie.net/naruto/images/0/0e/Kagari2.PNG",
    '529': "https://static.wikia.nocookie.net/naruto/images/0/04/Kageki.PNG",
    '531': "https://static.wikia.nocookie.net/naruto/images/2/26/Kagero.PNG",
    '540': 'https://qph.cf2.quoracdn.net/main-qimg-7f01c2e72f88b06bd9d0c0e943d17525-lq',
    '546': 'https://static.wikia.nocookie.net/naruto/images/d/d1/Kajika.PNG',
    '572': 'https://static.wikia.nocookie.net/naruto/images/7/7d/Kanabun.PNG',
    '580': 'https://static.wikia.nocookie.net/naruto/images/0/01/Suika.png/',
    '602': ['https://static.wikia.nocookie.net/naruto/images/f/fd/Kasumi1.jpg',
        'https://static.wikia.nocookie.net/naruto/images/c/ce/Kasumi_Unmasked.JPG'
    ],
    '604': "https://static.wikia.nocookie.net/naruto/images/4/44/Katazu.PNG",
    '628': "https://static.wikia.nocookie.net/naruto/images/3/3f/Kigiri.PNG",
    '629': 'https://static.wikia.nocookie.net/naruto/images/3/3c/Kih%C5%8D.PNG',
    '634': "https://static.wikia.nocookie.net/naruto/images/d/de/Kikuchiyo.png/",
    '638': "https://static.wikia.nocookie.net/naruto/images/d/d4/Kin.PNG",
    '640': 'https://static.wikia.nocookie.net/naruto/images/3/30/Outer_Path.PNG',
    '649': "https://static.wikia.nocookie.net/naruto/images/1/12/Kirisame.PNG",
    '664': 'https://static.wikia.nocookie.net/narutofanon/images/c/c0/Mukai_Kohinata.png/',
    '685': 'https://static.wikia.nocookie.net/naruto/images/e/ee/Minature_Nue.png/',
    '687': 'https://k.sinaimg.cn/n/front/265/w640h425/20180901/DGBN-hinpmnr3352198.jpg/w700d1q75cms.jpg',
    '688': 'https://k.sinaimg.cn/n/front/265/w640h425/20180901/DGBN-hinpmnr3352198.jpg/w700d1q75cms.jpg',
    '692': 'https://static.wikia.nocookie.net/naruto/images/8/80/Korobi.PNG',
    '697': 'https://static.wikia.nocookie.net/naruto/images/2/24/K%C5%8Dsuke.PNG',
    '705': 'https://static.wikia.nocookie.net/xianb/images/2/2d/Boruto_Naruto_Next_Generations_Episode_221_0853.jpg',
    '711': "https://static.wikia.nocookie.net/naruto/images/7/7b/Kurama2.png/",
    '717': "https://static.wikia.nocookie.net/naruto/images/1/1e/Kurobachi_Kamizuru.PNG",
    '732': "https://static.wikia.nocookie.net/naruto/images/f/f7/Kusune.PNG",
    '740': "https://static.wikia.nocookie.net/xianb/images/a/a2/Boruto_Naruto_Next_Generations_Episode_285_0037.jpg/",
    '752': "https://static.wikia.nocookie.net/naruto/images/2/21/Magire.png/",
    '763': 'https://static.wikia.nocookie.net/naruto/images/2/21/Margo.png',
    '768': 'https://static.wikia.nocookie.net/naruto/images/f/f3/Masako.PNG',
    '778': 'https://static.wikia.nocookie.net/naruto/images/4/4d/Mecha-Naruto.png/',
    '783': 'https://static.wikia.nocookie.net/naruto/images/c/c0/Messanger_Lizard.PNG',
    '789': 'https://static.wikia.nocookie.net/naruto/images/f/f6/Michy.PNG',
    '790': 'https://static.wikia.nocookie.net/naruto/images/3/3c/Midare.PNG',
    '802': 'https://static.wikia.nocookie.net/naruto/images/2/28/Tomaru_Minakura.JPG/',
    '839': 'https://static.wikia.nocookie.net/naruto/images/e/e8/Mouryou2.PNG',
    '845': 'https://static.wikia.nocookie.net/naruto/images/4/43/Mubi2.PNG',
    '851': 'https://static.wikia.nocookie.net/naruto/images/b/ba/Anrokuzan.PNG',
    '854': 'https://static.wikia.nocookie.net/naruto/images/2/23/Murasame.PNG',
    '855': 'https://static.wikia.nocookie.net/naruto/images/6/6a/Musai.PNG',
    '856': 'https://img2.wikia.nocookie.net/__cb20100420002102/naruto/images/5/54/Dokonj%C5%8D_Ninden_Protagonist.png',
    '870': 'https://static.wikia.nocookie.net/naruto/images/c/cf/Nango.PNG',
    '888': [
            'https://static.wikia.nocookie.net/naruto/images/4/4d/Nejiri.JPG/',
            'https://static.wikia.nocookie.net/naruto/images/d/dd/Nejiri.png'
            ],
    '900': 'https://static.wikia.nocookie.net/naruto/images/f/fc/Nishi.JPG/',
    '901': 'https://static.wikia.nocookie.net/naruto/images/b/b2/Nishi_Infobox.png/',
    '909': 'https://static.wikia.nocookie.net/naruto/images/c/c5/Nurari.PNG',
    '911': 'https://static.wikia.nocookie.net/naruto/images/5/51/Oboro.PNG',
    '1030': "https://static.wikia.nocookie.net/naruto/images/f/f1/S%C4%81ra%27s_Daughter.PNG",
    '1031': 'https://static.wikia.nocookie.net/naruto/images/f/fa/Sarai.PNG',
    '1032': "https://static.wikia.nocookie.net/naruto/images/4/47/Sari.PNG",
    '1039': 'https://static.wikia.nocookie.net/disneythehunchbackofnotredame/images/3/3a/Sasuke_Sarutobi_Anime.png',
    '1073': 'https://static.wikia.nocookie.net/naruto/images/4/4e/S%C4%93ramu.PNG',
    '1085': 'https://static.wikia.nocookie.net/naruto/images/d/dc/Shigure.PNG',
    '1090': 'https://static.wikia.nocookie.net/naruto/images/6/6d/Shikazo.PNG',
    '1104': 'https://static.wikia.nocookie.net/naruto/images/e/e1/Shion.PNG',
    '1143': 'https://static.wikia.nocookie.net/naruto/images/6/65/Suien.PNG',
    '1161': 'https://static.wikia.nocookie.net/naruto/images/e/e1/Susuki_%28Land_of_Demons%29.PNG',
    '1173': 'https://static.wikia.nocookie.net/naruto/images/4/43/Taiseki.PNG',
    '1185': 'https://static.wikia.nocookie.net/naruto/images/a/ab/Tami.PNG',
    '1187': 'https://static.wikia.nocookie.net/naruto/images/b/be/Tanishi.PNG',
    '1226': 'https://static.wikia.nocookie.net/naruto/images/d/d9/Tetsuru.PNG',
    '1265': 'https://static.wikia.nocookie.net/naruto/images/f/f3/Kin_Tsuchi.PNG',
    '1266': 'https://static.wikia.nocookie.net/naruto/images/2/23/Tsuchigumo_chief.PNG',
    '1270': 'https://static.wikia.nocookie.net/naruto/images/f/fe/Tsukado.PNG',
    '1290': 'https://static.wikia.nocookie.net/narutofanon/images/c/c6/Hazuki.jpg/',
    '1329': 'https://static.wikia.nocookie.net/naruto/images/c/cb/Hibachi%27s_friend.PNG',
    '1340': 'https://static.wikia.nocookie.net/naruto/images/f/f7/Himawari_Part_I.png',
    '1375': 'https://static.wikia.nocookie.net/naruto/images/7/76/Yaoki.PNG',
    '1376': 'https://static.wikia.nocookie.net/naruto/images/e/ef/YashamaruHD.PNG',
    '1417': 'https://static.wikia.nocookie.net/naruto/images/0/00/Yuto_Normal.PNG',
    '1424': 'https://static.wikia.nocookie.net/naruto/images/9/92/Zetsu_Online.png'
}


const sidebarData = [
    ['number', 0 ,2],
    ['A' , 3, 104],
    ['B', 105, 134],
    ['C', 135, 164],
    ['D', 165, 210],
    ['E', 211, 218],
    ['F', 219, 258],
    ['G', 259, 345],
    ['H', 346, 446],
    ['I', 447, 500],
    ['J', 501, 523],
    ['K', 524, 736],
    ['L', 737, 745],
    ['M', 746, 857],
    ['N', 858, 910],
    ['O', 911, 948],
    ['P', 949, 957],
    ['Q',0,0],
    ['R', 958, 998],
    ['S', 999, 1168],
    ['T', 1169, 1286],
    ['U', 1287, 1345],
    ['V', 1346, 1348],
    ['W', 1349, 1353],
    ['X', 0, 0],
    ['Y', 1354, 1417],
    ['Z', 1418, 1429]
]

